from annotator.data_generation.classes.kill_feed import KillFeedCTCGenerator
from annotator.data_generation.classes.mid import MidStatusGenerator
from annotator.data_generation.classes.player import PlayerStatusGenerator
from annotator.data_generation.classes.player_name import PlayerOCRGenerator
from annotator.data_generation.classes.ctc import CTCDataGenerator
from annotator.data_generation.classes.replay import ReplayStatusGenerator
from annotator.data_generation.classes.pause import PauseStatusGenerator
from annotator.data_generation.classes.game import GameGenerator